version: 2.1
orbs:
    puppeteer: threetreeslight/puppeteer@0.1.2
    slack: circleci/slack@3.4.2
commands:
  build_ts:
    description: Build js files from ts
    steps:
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/
jobs:
    build-test-monitor:
        docker:
            - image: cimg/node:14.17-browsers
        steps:
            - slack/notify:
                channel: C0137E8F72A
                color: '#42e2f4'
                message: Starting snyk-licenses build & monitor
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - build_ts
            - run:
                name: Run Tests
                command: npm test
            - run: npx semantic-release
            - slack/status:
                fail_only: true
                only_for_branches: master
    build-test:
        docker:
            - image: cimg/node:14.17-browsers
        steps:
            - slack/notify:
                channel: C0137E8F72A
                color: '#42e2f4'
                message: Starting snyk-licenses test
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - build_ts
            - run: npm test
            - slack/status:
                fail_only: true
                only_for_branches: master
    build-test-from-fork:
        docker:
            - image: cimg/node:14.17-browsers
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - run: npm test
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-monitor:
                context: SNYK

    build-test-monitor:
        jobs:
            - build-test-monitor:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
